// Copyright 2026 SIROS Foundation. BSD 2-Clause License.

//! Differential conformance tests against `test-vectors/emlun_reference.json`.
//!
//! That file is generated by running Emil Lundberg's TypeScript
//! implementation (`emlun/wallet-common@blind-bbs-schnorr`, `src/bbs/`) via
//! the dump script described in `PROFILE.md` §5. It is ground truth for this
//! port: every value here was produced by the reference implementation, not
//! transcribed by hand.

use serde_json::Value;
use zk_cred_bbs::bbs::{Ser, serialize};
use zk_cred_bbs::suite::Suite;
use zk_cred_bbs::util::expand_message_xmd;

fn vectors() -> Value {
  let raw = include_str!("../test-vectors/emlun_reference.json");
  serde_json::from_str(raw).expect("reference vectors are valid JSON")
}

fn hex_of(v: &Value) -> Vec<u8> {
  hex::decode(v.as_str().expect("hex string")).expect("valid hex")
}

fn hex_list(v: &Value) -> Vec<Vec<u8>> {
  v.as_array().expect("array").iter().map(hex_of).collect()
}

#[test]
fn expand_message_xmd_matches_reference() {
  let v = vectors();
  let cases = v["expand_message_xmd"].as_array().unwrap();
  assert!(!cases.is_empty());
  for (i, case) in cases.iter().enumerate() {
    let out = expand_message_xmd(&hex_of(&case["msg"]), &hex_of(&case["dst"]), case["len"].as_u64().unwrap() as usize).unwrap();
    assert_eq!(hex::encode(&out), case["out"].as_str().unwrap(), "case {i}");
  }
}

#[test]
fn hash_to_scalar_matches_reference() {
  let v = vectors();
  let suite = Suite::default();
  for (i, case) in v["hash_to_scalar"].as_array().unwrap().iter().enumerate() {
    let s = suite.hash_to_scalar(&hex_of(&case["msg"]), &hex_of(&case["dst"])).unwrap();
    assert_eq!(hex::encode(serialize(&[Ser::Scalar(s)])), case["scalar"].as_str().unwrap(), "case {i}");
  }
}

#[test]
fn create_generators_matches_reference() {
  let v = vectors();
  let suite = Suite::default();
  let cg = &v["create_generators"];
  // The reference dump uses the suite's own api_id; if that ever diverges
  // the rest of the comparison is meaningless, so check it explicitly.
  assert_eq!(hex::encode(&suite.api_id), cg["api_id"].as_str().unwrap());

  let count = cg["count"].as_u64().unwrap() as usize;
  let generators = suite.create_generators(count).unwrap();
  let expected = cg["points"].as_array().unwrap();
  assert_eq!(generators.len(), expected.len());
  for (i, (got, want)) in generators.iter().zip(expected).enumerate() {
    assert_eq!(hex::encode(serialize(&[Ser::G1(*got)])), want.as_str().unwrap(), "generator {i}");
  }
}

#[test]
fn messages_to_scalars_matches_reference() {
  let v = vectors();
  let suite = Suite::default();
  let messages = hex_list(&v["messages_to_scalars"]["messages"]);
  let scalars = suite.messages_to_scalars(&messages).unwrap();
  let expected = v["messages_to_scalars"]["scalars"].as_array().unwrap();
  assert_eq!(scalars.len(), expected.len());
  for (i, (got, want)) in scalars.iter().zip(expected).enumerate() {
    assert_eq!(hex::encode(serialize(&[Ser::Scalar(*got)])), want.as_str().unwrap(), "scalar {i}");
  }
}

#[test]
fn sign_matches_reference_and_verifies() {
  let v = vectors();
  let suite = Suite::default();
  let s = &v["sign"];

  let sk = zk_cred_bbs::bbs::scalar_from_be(&hex_of(&s["sk"])).unwrap();
  let pk = hex_of(&s["pk"]);
  let header = hex_of(&s["header"]);
  let messages = hex_list(&s["messages"]);

  let signature = suite.sign(&sk, &pk, &header, &messages).unwrap();
  assert_eq!(
    hex::encode(&signature),
    s["signature"].as_str().unwrap(),
    "signature must match the reference implementation byte for byte"
  );

  // And our own verifier must accept it.
  suite.verify(&pk, &signature, &header, &messages).unwrap();
}

#[test]
fn verify_rejects_tampering() {
  let v = vectors();
  let suite = Suite::default();
  let s = &v["sign"];
  let pk = hex_of(&s["pk"]);
  let header = hex_of(&s["header"]);
  let mut messages = hex_list(&s["messages"]);
  let signature = hex_of(&s["signature"]);

  // A flipped message must not verify under the same signature.
  messages[0][0] ^= 0x01;
  assert!(suite.verify(&pk, &signature, &header, &messages).is_err());

  // Nor a flipped header.
  let messages = hex_list(&s["messages"]);
  let mut bad_header = header.clone();
  bad_header[0] ^= 0x01;
  assert!(suite.verify(&pk, &signature, &bad_header, &messages).is_err());

  // Nor a corrupted signature.
  let mut bad_sig = signature.clone();
  let last = bad_sig.len() - 1;
  bad_sig[last] ^= 0x01;
  assert!(suite.verify(&pk, &bad_sig, &header, &messages).is_err());
}

/// The commitment half of the real-hardware key binding vector (§1.4 of the
/// plan): commit challenge, commitment, and the issuer's blind signature,
/// all against device signatures captured from an actual YubiKey prototype.
#[test]
fn hardware_keybind_commit_and_blind_sign_match_reference() {
  use zk_cred_bbs::blind::BlindSuite;
  use zk_cred_bbs::keybind::SchnorrBls12381;
  use zk_cred_bbs::suite::ScalarSource;

  let v = vectors();
  let hw = &v["hardware_keybind"];

  let suite = BlindSuite::new(
    Suite::new(ScalarSource::Seeded {
      seed: hex_of(&hw["mock_seed"]),
      dst: hex_of(&hw["mock_dst"]),
    }),
    SchnorrBls12381,
    zk_cred_bbs::blind::SCHNORR_SUITE_ID,
  );

  let keybind_public_keys = hex_list(&hw["keybind_public_keys"]);
  let committed_messages = hex_list(&hw["committed_messages"]);
  let commit_sigs = hex_list(&hw["keybind_commit_signatures"]);

  let (state, secret_prover_blind, challenge) = suite.commit_init(&committed_messages, &keybind_public_keys).unwrap();

  assert_eq!(
    hex::encode(serialize(&[Ser::Scalar(challenge)])),
    hw["commit_challenge"].as_str().unwrap(),
    "commit challenge — this is what the device signs"
  );
  assert_eq!(
    hex::encode(serialize(&[Ser::Scalar(secret_prover_blind)])),
    hw["secret_prover_blind"].as_str().unwrap(),
    "secret_prover_blind is long-lived credential state"
  );

  let commitment_with_proof = suite.commit_finalize(&state, &commit_sigs).unwrap();
  assert_eq!(
    hex::encode(&commitment_with_proof),
    hw["commitment_with_proof"].as_str().unwrap(),
    "commitment sent to the issuer"
  );

  // Issuer side: verify the commitment (including the device's proof of
  // possession) and blind-sign it.
  let sk = zk_cred_bbs::bbs::scalar_from_be(&hex_of(&hw["sk"])).unwrap();
  let pk = hex_of(&hw["pk"]);
  let header = hex_of(&hw["header"]);
  let signer_messages = hex_list(&hw["signer_messages"]);

  let signature = suite.blind_sign(&sk, &pk, &commitment_with_proof, &header, &signer_messages).unwrap();
  assert_eq!(hex::encode(&signature), hw["signature"].as_str().unwrap(), "blind signature");

  // Holder side: the credential must validate before being stored.
  let mut all_messages = signer_messages.clone();
  all_messages.extend(committed_messages.iter().cloned());
  suite
    .verify_blind_sign(
      &pk,
      &signature,
      &header,
      &all_messages,
      signer_messages.len(),
      &keybind_public_keys,
      &secret_prover_blind,
    )
    .unwrap();
}

/// The presentation half of the hardware vector: generate a proof using
/// device signatures captured from a real YubiKey prototype, check it is
/// byte-identical to the reference implementation's, and verify it.
#[test]
fn hardware_keybind_proof_matches_reference_and_verifies() {
  use std::str::FromStr;
  use zk_cred_bbs::blind::{BlindSuite, Disclosure, SCHNORR_SUITE_ID};
  use zk_cred_bbs::keybind::SchnorrBls12381;
  use zk_cred_bbs::suite::ScalarSource;

  let v = vectors();
  let hw = &v["hardware_keybind"];

  let suite = BlindSuite::new(
    Suite::new(ScalarSource::Seeded {
      seed: hex_of(&hw["mock_seed"]),
      dst: hex_of(&hw["mock_dst"]),
    }),
    SchnorrBls12381,
    SCHNORR_SUITE_ID,
  );

  let pk = hex_of(&hw["pk"]);
  let header = hex_of(&hw["header"]);
  let ph = hex_of(&hw["presentation_header"]);
  let signer_messages = hex_list(&hw["signer_messages"]);
  let committed_messages = hex_list(&hw["committed_messages"]);
  let keybind_public_keys = hex_list(&hw["keybind_public_keys"]);
  let proof_sigs = hex_list(&hw["keybind_proof_signatures"]);
  let signature = hex_of(&hw["signature"]);
  let secret_prover_blind = zk_cred_bbs::bbs::scalar_from_be(&hex_of(&hw["secret_prover_blind"])).unwrap();

  let disclosures: Vec<Disclosure> = hw["disclosures"]
    .as_array()
    .unwrap()
    .iter()
    .map(|d| Disclosure::from_str(d.as_str().unwrap()).unwrap())
    .collect();

  let mut all_messages = signer_messages.clone();
  all_messages.extend(committed_messages.iter().cloned());

  let (state, _add_zkp_info, dpk_challenges) = suite
    .blind_proof_gen_init(
      &pk,
      &signature,
      &header,
      &ph,
      &all_messages,
      signer_messages.len(),
      &disclosures,
      &keybind_public_keys,
      &secret_prover_blind,
    )
    .unwrap();

  // The challenges handed to the authenticator must match exactly — these
  // are what the captured device signatures were produced over.
  let expected_challenges = hw["dpk_challenges"].as_array().unwrap();
  assert_eq!(dpk_challenges.len(), expected_challenges.len());
  for (i, (got, want)) in dpk_challenges.iter().zip(expected_challenges).enumerate() {
    assert_eq!(
      hex::encode(got),
      want.as_str().unwrap(),
      "key binding challenge {i} — the exact bytes handed to the authenticator"
    );
  }

  let proof = suite.blind_proof_gen_finalize(&state, &proof_sigs).unwrap();
  assert_eq!(
    hex::encode(&proof),
    hw["proof"].as_str().unwrap(),
    "proof must match the reference implementation byte for byte"
  );

  let disclosed_messages: Vec<Vec<u8>> = all_messages
    .iter()
    .zip(disclosures.iter())
    .filter(|(_, d)| **d == Disclosure::Disclose)
    .map(|(m, _)| m.clone())
    .collect();

  suite
    .blind_proof_verify(&pk, &proof, &header, &ph, signer_messages.len(), &disclosed_messages, &disclosures)
    .unwrap();
}
