// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(zk_cred_bbsFFI)
import zk_cred_bbsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_zk_cred_bbs_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_zk_cred_bbs_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureZkCredBbsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Opaque error type crossing the UniFFI boundary.
 */
public protocol BbsFfiErrorProtocol: AnyObject, Sendable {
    
    /**
     * Human-readable description, for logging and diagnostics only —
     * never surface this to a relying party.
     */
    func message()  -> String
    
}
/**
 * Opaque error type crossing the UniFFI boundary.
 */
open class BbsFfiError: BbsFfiErrorProtocol, @unchecked Sendable, Swift.Error, Foundation.LocalizedError {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_zk_cred_bbs_fn_clone_bbsffierror(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_zk_cred_bbs_fn_free_bbsffierror(handle, $0) }
    }

    

    
    /**
     * Human-readable description, for logging and diagnostics only —
     * never surface this to a relying party.
     */
open func message() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_zk_cred_bbs_fn_method_bbsffierror_message(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBbsFfiError: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = BbsFfiError

    public static func lift(_ handle: UInt64) throws -> BbsFfiError {
        return BbsFfiError(unsafeFromHandle: handle)
    }

    public static func lower(_ value: BbsFfiError) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BbsFfiError {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: BbsFfiError, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsFfiError_lift(_ handle: UInt64) throws -> BbsFfiError {
    return try FfiConverterTypeBbsFfiError.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsFfiError_lower(_ value: BbsFfiError) -> UInt64 {
    return FfiConverterTypeBbsFfiError.lower(value)
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBbsFfiError__as_error: FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> BbsFfiError {
        var reader = createReader(data: Data(rustBuffer: buf))
        return try FfiConverterTypeBbsFfiError.read(from: &reader)
    }

    public static func lower(_ value: BbsFfiError) -> RustBuffer {
        fatalError("not implemented")
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BbsFfiError {
        fatalError("not implemented")
    }

    public static func write(_ value: BbsFfiError, into buf: inout [UInt8]) {
        fatalError("not implemented")
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsFfiError__as_error_lift(_ buf: RustBuffer) throws -> BbsFfiError {
    return try FfiConverterTypeBbsFfiError__as_error.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsFfiError__as_error_lower(_ value: BbsFfiError) -> RustBuffer {
    return FfiConverterTypeBbsFfiError__as_error.lower(value)
}


/**
 * Output of [`commit_init`].
 */
public struct CommitInitResult: Equatable, Hashable {
    /**
     * Opaque state to hand back to [`commit_finalize`]. Not secret, but
     * not useful to anyone else either.
     */
    public var state: Data
    /**
     * **Long-lived credential secret.** Must be stored alongside the
     * credential and is required for every future presentation; losing it
     * makes the credential unusable, and it must never leave the wallet.
     */
    public var secretProverBlind: Data
    /**
     * The challenge for the authenticator to sign, once per key binding
     * key.
     */
    public var challenge: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque state to hand back to [`commit_finalize`]. Not secret, but
         * not useful to anyone else either.
         */state: Data, 
        /**
         * **Long-lived credential secret.** Must be stored alongside the
         * credential and is required for every future presentation; losing it
         * makes the credential unusable, and it must never leave the wallet.
         */secretProverBlind: Data, 
        /**
         * The challenge for the authenticator to sign, once per key binding
         * key.
         */challenge: Data) {
        self.state = state
        self.secretProverBlind = secretProverBlind
        self.challenge = challenge
    }

    

    
}

#if compiler(>=6)
extension CommitInitResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCommitInitResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CommitInitResult {
        return
            try CommitInitResult(
                state: FfiConverterData.read(from: &buf), 
                secretProverBlind: FfiConverterData.read(from: &buf), 
                challenge: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: CommitInitResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.state, into: &buf)
        FfiConverterData.write(value.secretProverBlind, into: &buf)
        FfiConverterData.write(value.challenge, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommitInitResult_lift(_ buf: RustBuffer) throws -> CommitInitResult {
    return try FfiConverterTypeCommitInitResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommitInitResult_lower(_ value: CommitInitResult) -> RustBuffer {
    return FfiConverterTypeCommitInitResult.lower(value)
}


/**
 * Output of [`blind_proof_gen_init`].
 */
public struct ProofGenInitResult: Equatable, Hashable {
    /**
     * Opaque state to hand back to [`blind_proof_gen_finalize`].
     */
    public var state: Data
    /**
     * One challenge per key binding key, already SHA-256'd — hand each
     * straight to the authenticator as the message to be signed. See
     * `PROFILE.md` DELTA 3 for why the prehash is here.
     */
    public var keybindChallenges: [Data]
    /**
     * Values of the messages marked `Commit`, in order.
     */
    public var committedValues: [Data]
    /**
     * Blinding factors for those commitments, in the same order.
     */
    public var committedBlindings: [Data]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque state to hand back to [`blind_proof_gen_finalize`].
         */state: Data, 
        /**
         * One challenge per key binding key, already SHA-256'd — hand each
         * straight to the authenticator as the message to be signed. See
         * `PROFILE.md` DELTA 3 for why the prehash is here.
         */keybindChallenges: [Data], 
        /**
         * Values of the messages marked `Commit`, in order.
         */committedValues: [Data], 
        /**
         * Blinding factors for those commitments, in the same order.
         */committedBlindings: [Data]) {
        self.state = state
        self.keybindChallenges = keybindChallenges
        self.committedValues = committedValues
        self.committedBlindings = committedBlindings
    }

    

    
}

#if compiler(>=6)
extension ProofGenInitResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofGenInitResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofGenInitResult {
        return
            try ProofGenInitResult(
                state: FfiConverterData.read(from: &buf), 
                keybindChallenges: FfiConverterSequenceData.read(from: &buf), 
                committedValues: FfiConverterSequenceData.read(from: &buf), 
                committedBlindings: FfiConverterSequenceData.read(from: &buf)
        )
    }

    public static func write(_ value: ProofGenInitResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.state, into: &buf)
        FfiConverterSequenceData.write(value.keybindChallenges, into: &buf)
        FfiConverterSequenceData.write(value.committedValues, into: &buf)
        FfiConverterSequenceData.write(value.committedBlindings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofGenInitResult_lift(_ buf: RustBuffer) throws -> ProofGenInitResult {
    return try FfiConverterTypeProofGenInitResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofGenInitResult_lower(_ value: ProofGenInitResult) -> RustBuffer {
    return FfiConverterTypeProofGenInitResult.lower(value)
}


/**
 * Per-message disclosure choice at presentation time.
 */

public enum BbsDisclosure: Equatable, Hashable {
    
    case disclose
    case hide
    case commit





}

#if compiler(>=6)
extension BbsDisclosure: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBbsDisclosure: FfiConverterRustBuffer {
    typealias SwiftType = BbsDisclosure

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BbsDisclosure {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disclose
        
        case 2: return .hide
        
        case 3: return .commit
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BbsDisclosure, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disclose:
            writeInt(&buf, Int32(1))
        
        
        case .hide:
            writeInt(&buf, Int32(2))
        
        
        case .commit:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsDisclosure_lift(_ buf: RustBuffer) throws -> BbsDisclosure {
    return try FfiConverterTypeBbsDisclosure.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsDisclosure_lower(_ value: BbsDisclosure) -> RustBuffer {
    return FfiConverterTypeBbsDisclosure.lower(value)
}



/**
 * Which key binding construction, and therefore which domain separation,
 * this credential uses.
 */

public enum BbsSuiteId: Equatable, Hashable {
    
    /**
     * Blind BBS with no device binding.
     */
    case plain
    /**
     * Blind BBS with Schnorr-on-BLS12-381-G1 device binding — the profile
     * in `PROFILE.md`.
     */
    case schnorr





}

#if compiler(>=6)
extension BbsSuiteId: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBbsSuiteId: FfiConverterRustBuffer {
    typealias SwiftType = BbsSuiteId

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BbsSuiteId {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .plain
        
        case 2: return .schnorr
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BbsSuiteId, into buf: inout [UInt8]) {
        switch value {
        
        
        case .plain:
            writeInt(&buf, Int32(1))
        
        
        case .schnorr:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsSuiteId_lift(_ buf: RustBuffer) throws -> BbsSuiteId {
    return try FfiConverterTypeBbsSuiteId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBbsSuiteId_lower(_ value: BbsSuiteId) -> RustBuffer {
    return FfiConverterTypeBbsSuiteId.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBbsDisclosure: FfiConverterRustBuffer {
    typealias SwiftType = [BbsDisclosure]

    public static func write(_ value: [BbsDisclosure], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBbsDisclosure.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BbsDisclosure] {
        let len: Int32 = try readInt(&buf)
        var seq = [BbsDisclosure]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBbsDisclosure.read(from: &buf))
        }
        return seq
    }
}
/**
 * Complete the presentation with the authenticator's signatures.
 */
public func blindProofGenFinalize(suiteId: BbsSuiteId, state: Data, keybindSignatures: [Data])throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeBbsFfiError__as_error_lift) {
        uniffiCallStatus in
    uniffi_zk_cred_bbs_fn_func_blind_proof_gen_finalize(
        FfiConverterTypeBbsSuiteId_lower(suiteId),
        FfiConverterData.lower(state),
        FfiConverterSequenceData.lower(keybindSignatures),uniffiCallStatus
    )
})
}
/**
 * Begin a presentation. Sign each returned `keybind_challenges` entry with
 * the corresponding authenticator, then call
 * [`blind_proof_gen_finalize`].
 */
public func blindProofGenInit(suiteId: BbsSuiteId, publicKey: Data, signature: Data, header: Data, presentationHeader: Data, messages: [Data], issuerKnownMessagesNo: UInt32, disclosures: [BbsDisclosure], keybindPublicKeys: [Data], secretProverBlind: Data)throws  -> ProofGenInitResult  {
    return try  FfiConverterTypeProofGenInitResult_lift(try rustCallWithError(FfiConverterTypeBbsFfiError__as_error_lift) {
        uniffiCallStatus in
    uniffi_zk_cred_bbs_fn_func_blind_proof_gen_init(
        FfiConverterTypeBbsSuiteId_lower(suiteId),
        FfiConverterData.lower(publicKey),
        FfiConverterData.lower(signature),
        FfiConverterData.lower(header),
        FfiConverterData.lower(presentationHeader),
        FfiConverterSequenceData.lower(messages),
        FfiConverterUInt32.lower(issuerKnownMessagesNo),
        FfiConverterSequenceTypeBbsDisclosure.lower(disclosures),
        FfiConverterSequenceData.lower(keybindPublicKeys),
        FfiConverterData.lower(secretProverBlind),uniffiCallStatus
    )
})
}
/**
 * Verify a presentation. Exposed here mainly so a wallet can check its own
 * output in tests — a real relying party verifies in Go, over the C ABI in
 * `go_ffi.rs`.
 */
public func blindProofVerify(suiteId: BbsSuiteId, publicKey: Data, proof: Data, header: Data, presentationHeader: Data, issuerKnownMessagesNo: UInt32, disclosedMessages: [Data], disclosures: [BbsDisclosure])throws   {try rustCallWithError(FfiConverterTypeBbsFfiError__as_error_lift) {
        uniffiCallStatus in
    uniffi_zk_cred_bbs_fn_func_blind_proof_verify(
        FfiConverterTypeBbsSuiteId_lower(suiteId),
        FfiConverterData.lower(publicKey),
        FfiConverterData.lower(proof),
        FfiConverterData.lower(header),
        FfiConverterData.lower(presentationHeader),
        FfiConverterUInt32.lower(issuerKnownMessagesNo),
        FfiConverterSequenceData.lower(disclosedMessages),
        FfiConverterSequenceTypeBbsDisclosure.lower(disclosures),uniffiCallStatus
    )
}
}
/**
 * Complete the commitment with the authenticator's signatures. The result
 * is what goes to the issuer.
 */
public func commitFinalize(suiteId: BbsSuiteId, state: Data, keybindSignatures: [Data])throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeBbsFfiError__as_error_lift) {
        uniffiCallStatus in
    uniffi_zk_cred_bbs_fn_func_commit_finalize(
        FfiConverterTypeBbsSuiteId_lower(suiteId),
        FfiConverterData.lower(state),
        FfiConverterSequenceData.lower(keybindSignatures),uniffiCallStatus
    )
})
}
/**
 * Begin blind issuance: commit to the messages the issuer will not see, and
 * to the key binding public keys.
 *
 * The returned `challenge` must be signed by each authenticator before
 * calling [`commit_finalize`].
 */
public func commitInit(suiteId: BbsSuiteId, committedMessages: [Data], keybindPublicKeys: [Data])throws  -> CommitInitResult  {
    return try  FfiConverterTypeCommitInitResult_lift(try rustCallWithError(FfiConverterTypeBbsFfiError__as_error_lift) {
        uniffiCallStatus in
    uniffi_zk_cred_bbs_fn_func_commit_init(
        FfiConverterTypeBbsSuiteId_lower(suiteId),
        FfiConverterSequenceData.lower(committedMessages),
        FfiConverterSequenceData.lower(keybindPublicKeys),uniffiCallStatus
    )
})
}
/**
 * Check that the issuer signed what it was supposed to.
 *
 * **Call this before storing a credential.** An issuer that signed a
 * different message set, or bound a different key, produces a credential
 * that fails at presentation time with no useful diagnostic.
 */
public func verifyBlindSign(suiteId: BbsSuiteId, publicKey: Data, signature: Data, header: Data, messages: [Data], issuerKnownMessagesNo: UInt32, keybindPublicKeys: [Data], secretProverBlind: Data)throws   {try rustCallWithError(FfiConverterTypeBbsFfiError__as_error_lift) {
        uniffiCallStatus in
    uniffi_zk_cred_bbs_fn_func_verify_blind_sign(
        FfiConverterTypeBbsSuiteId_lower(suiteId),
        FfiConverterData.lower(publicKey),
        FfiConverterData.lower(signature),
        FfiConverterData.lower(header),
        FfiConverterSequenceData.lower(messages),
        FfiConverterUInt32.lower(issuerKnownMessagesNo),
        FfiConverterSequenceData.lower(keybindPublicKeys),
        FfiConverterData.lower(secretProverBlind),uniffiCallStatus
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_zk_cred_bbs_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_zk_cred_bbs_checksum_func_blind_proof_gen_finalize() != 33447) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zk_cred_bbs_checksum_func_blind_proof_gen_init() != 10709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zk_cred_bbs_checksum_func_blind_proof_verify() != 28899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zk_cred_bbs_checksum_func_commit_finalize() != 30749) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zk_cred_bbs_checksum_func_commit_init() != 41686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zk_cred_bbs_checksum_func_verify_blind_sign() != 2199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zk_cred_bbs_checksum_method_bbsffierror_message() != 7094) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureZkCredBbsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all