// Copyright 2026 SIROS Foundation. BSD 2-Clause License.

// Exercises the real staticlib against the same reference vectors the Rust
// tests use, so a mistake in the hand-written header, in argument order, or
// in the ownership contract surfaces here rather than in a Go service.
package bbs

import (
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

type vectors struct {
	HardwareKeybind struct {
		PK                  string   `json:"pk"`
		SK                  string   `json:"sk"`
		Header              string   `json:"header"`
		PresentationHeader  string   `json:"presentation_header"`
		SignerMessages      []string `json:"signer_messages"`
		CommittedMessages   []string `json:"committed_messages"`
		CommitmentWithProof string   `json:"commitment_with_proof"`
		Signature           string   `json:"signature"`
		Proof               string   `json:"proof"`
		Disclosures         []string `json:"disclosures"`
	} `json:"hardware_keybind"`
}

func load(t *testing.T) *vectors {
	t.Helper()
	raw, err := os.ReadFile("../test-vectors/emlun_reference.json")
	if err != nil {
		t.Fatalf("reading vectors: %v", err)
	}
	v := &vectors{}
	if err := json.Unmarshal(raw, v); err != nil {
		t.Fatalf("parsing vectors: %v", err)
	}
	return v
}

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex: %v", err)
	}
	return b
}

func decodeAll(t *testing.T, in []string) [][]byte {
	t.Helper()
	out := make([][]byte, len(in))
	for i, s := range in {
		out[i] = unhex(t, s)
	}
	return out
}

func disclosures(t *testing.T, names []string) []Disclosure {
	t.Helper()
	out := make([]Disclosure, len(names))
	for i, n := range names {
		switch n {
		case "DISCLOSE":
			out[i] = Disclose
		case "HIDE":
			out[i] = Hide
		case "COMMIT":
			out[i] = Commit
		default:
			t.Fatalf("unknown disclosure %q", n)
		}
	}
	return out
}

// The issuer path. The signature must match what the Rust and TypeScript
// implementations produce, byte for byte, over the C ABI.
func TestBlindSignMatchesReference(t *testing.T) {
	hw := load(t).HardwareKeybind

	got, err := Native{}.BlindSign(SuiteSchnorr,
		unhex(t, hw.SK), unhex(t, hw.PK),
		unhex(t, hw.CommitmentWithProof), unhex(t, hw.Header),
		decodeAll(t, hw.SignerMessages))
	if err != nil {
		t.Fatalf("BlindSign: %v", err)
	}
	if hex.EncodeToString(got) != hw.Signature {
		t.Fatalf("signature mismatch over the C ABI\n got: %s\nwant: %s",
			hex.EncodeToString(got), hw.Signature)
	}
}

func TestBlindSignRejectsBadCommitment(t *testing.T) {
	hw := load(t).HardwareKeybind

	commitment := unhex(t, hw.CommitmentWithProof)
	commitment[len(commitment)-1] ^= 0x01

	_, err := Native{}.BlindSign(SuiteSchnorr,
		unhex(t, hw.SK), unhex(t, hw.PK), commitment, unhex(t, hw.Header),
		decodeAll(t, hw.SignerMessages))
	if err == nil {
		t.Fatal("issuer blind-signed a commitment with a corrupted key binding signature")
	}
}

func TestVerifyProof(t *testing.T) {
	hw := load(t).HardwareKeybind
	disc := disclosures(t, hw.Disclosures)

	all := append(decodeAll(t, hw.SignerMessages), decodeAll(t, hw.CommittedMessages)...)
	var disclosed [][]byte
	for i, m := range all {
		if disc[i] == Disclose {
			disclosed = append(disclosed, m)
		}
	}

	verify := func(proof []byte) error {
		return Native{}.VerifyProof(SuiteSchnorr, unhex(t, hw.PK), proof,
			unhex(t, hw.Header), unhex(t, hw.PresentationHeader),
			len(hw.SignerMessages), disclosed, disc)
	}

	if err := verify(unhex(t, hw.Proof)); err != nil {
		t.Fatalf("valid proof rejected: %v", err)
	}

	bad := unhex(t, hw.Proof)
	bad[len(bad)/2] ^= 0x01
	if err := verify(bad); err == nil {
		t.Fatal("a tampered proof was accepted")
	}
}

// An unknown suite selector must be an error, not a silent fallback to a
// suite the caller did not ask for.
func TestUnknownSuiteIsRejected(t *testing.T) {
	hw := load(t).HardwareKeybind
	verifier := Native{}
	err := verifier.VerifyProof(Suite(99), unhex(t, hw.PK), unhex(t, hw.Proof),
		nil, nil, 0, nil, nil)
	if err == nil {
		t.Fatal("an unknown suite selector was accepted")
	}
}

// Repeated calls must not corrupt state or leak in a way that breaks the
// next call — the cheapest available check that the ownership contract holds.
func TestRepeatedCallsAreStable(t *testing.T) {
	hw := load(t).HardwareKeybind
	signer := Native{}
	for i := 0; i < 50; i++ {
		_, err := signer.BlindSign(SuiteSchnorr,
			unhex(t, hw.SK), unhex(t, hw.PK),
			unhex(t, hw.CommitmentWithProof), unhex(t, hw.Header),
			decodeAll(t, hw.SignerMessages))
		if err != nil {
			t.Fatalf("iteration %d: %v", i, err)
		}
	}
}

// --- container: issuance and verification through the C ABI ---------------

// jwpCase is one case from test-vectors/sdk_jwp_fixture.json, generated by
// `make sdk-fixture`. It carries both halves of the flow: what the issuer
// needs to build a credential, and a finished presentation for the verifier
// - because Go can do neither of the holder-side steps between them.
type jwpCase struct {
	IssuedJWP      string          `json:"issued_jwp"`
	PresentedJWP   string          `json:"presented_jwp"`
	Commitment     string          `json:"commitment"`
	IssuerPK       string          `json:"issuer_pk"`
	IssuerSK       string          `json:"issuer_sk"`
	IssuerClaims   json.RawMessage `json:"issuer_claims"`
	HolderPointers []string        `json:"holder_pointers"`
	Vct            string          `json:"vct"`
}

type jwpFixture struct {
	Cases map[string]jwpCase `json:"cases"`
}

func loadJWP(t *testing.T, name string) jwpCase {
	t.Helper()
	raw, err := os.ReadFile("../test-vectors/sdk_jwp_fixture.json")
	if err != nil {
		t.Fatalf("reading fixture: %v", err)
	}
	f := &jwpFixture{}
	if err := json.Unmarshal(raw, f); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	c, ok := f.Cases[name]
	if !ok {
		t.Fatalf("fixture has no %q case", name)
	}
	return c
}

func issueParams(t *testing.T, name string, kb KeyBinding, suite Suite) IssueParams {
	t.Helper()
	c := loadJWP(t, name)
	return IssueParams{
		Suite:          suite,
		SecretKey:      unhex(t, c.IssuerSK),
		PublicKey:      unhex(t, c.IssuerPK),
		Commitment:     unhex(t, c.Commitment),
		Vct:            c.Vct,
		IssuerClaims:   c.IssuerClaims,
		HolderPointers: c.HolderPointers,
		ExtraHeader:    json.RawMessage(`{"iss":"https://issuer.test"}`),
		KeyBinding:     kb,
	}
}

// The whole point of putting the container in the crate: a credential the
// Go issuer builds must be byte-identical to one the Rust side builds from
// the same inputs.
//
// Byte-identical is a fair demand here because nothing in issuance is
// randomised - the blinding all lives in the holder's commitment, which is
// an input. If the two ever disagree by so much as a key order in the
// header, every proof against this credential fails, and nothing in that
// failure says why. This is the test that catches it.
func TestIssueMatchesTheRustSide(t *testing.T) {
	for _, tc := range []struct {
		name string
		kb   KeyBinding
		suite Suite
	}{
		{"plain", NoKeyBinding, SuitePlain},
		{"keybind", SchnorrKeyBinding, SuiteSchnorr},
	} {
		t.Run(tc.name, func(t *testing.T) {
			want := loadJWP(t, tc.name).IssuedJWP
			got, err := Native{}.Issue(issueParams(t, tc.name, tc.kb, tc.suite))
			if err != nil {
				t.Fatalf("Issue: %v", err)
			}
			if got != want {
				t.Fatalf("credential differs from the one Rust builds\n got: %s\nwant: %s", got, want)
			}
		})
	}
}

// Issuance is deterministic, so calling twice must give the same answer -
// and neither call may disturb the other through the FFI.
func TestIssueIsStableAcrossCalls(t *testing.T) {
	p := issueParams(t, "plain", NoKeyBinding, SuitePlain)
	first, err := Native{}.Issue(p)
	if err != nil {
		t.Fatalf("first Issue: %v", err)
	}
	for i := 0; i < 5; i++ {
		again, err := Native{}.Issue(p)
		if err != nil {
			t.Fatalf("Issue %d: %v", i, err)
		}
		if again != first {
			t.Fatalf("Issue %d differs from the first", i)
		}
	}
}

// Each of these would produce a credential whose message vector is not what
// the header says it is - the failure mode the container exists to prevent.
func TestIssueRejectsAMisdescribedCredential(t *testing.T) {
	for _, tc := range []struct {
		name   string
		mutate func(*IssueParams)
	}{
		{"a holder pointer count that does not match the commitment", func(p *IssueParams) {
			p.HolderPointers = append(p.HolderPointers, "/an_extra_claim")
		}},
		{"no holder pointers at all when the commitment has one", func(p *IssueParams) {
			p.HolderPointers = nil
		}},
		{"a duplicate holder pointer", func(p *IssueParams) {
			p.HolderPointers = []string{"/device_pin_hash", "/device_pin_hash"}
		}},
		{"a holder pointer that is not an RFC 6901 pointer", func(p *IssueParams) {
			p.HolderPointers = []string{"device_pin_hash"}
		}},
		{"claims that are not a JSON object", func(p *IssueParams) {
			p.IssuerClaims = json.RawMessage(`["not","an","object"]`)
		}},
		{"claims that are not JSON at all", func(p *IssueParams) {
			p.IssuerClaims = json.RawMessage(`{`)
		}},
		{"no claims to sign", func(p *IssueParams) {
			p.IssuerClaims = json.RawMessage(`{}`)
		}},
		{"an extra header parameter restating a reserved one", func(p *IssueParams) {
			p.ExtraHeader = json.RawMessage(`{"cmap":{"smuggled":[0,false]}}`)
		}},
		{"a corrupted commitment", func(p *IssueParams) {
			c := append([]byte(nil), p.Commitment...)
			c[len(c)-1] ^= 0x01
			p.Commitment = c
		}},
		{"an unknown key binding selector", func(p *IssueParams) {
			p.KeyBinding = KeyBinding(99)
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := issueParams(t, "plain", NoKeyBinding, SuitePlain)
			tc.mutate(&p)
			if _, err := (Native{}).Issue(p); err == nil {
				t.Fatal("issuer accepted it")
			}
		})
	}
}

// The relying party's whole job, over the C ABI: verify a presentation and
// learn exactly what it disclosed.
func TestVerifyPresentation(t *testing.T) {
	c := loadJWP(t, "plain")
	got, err := Native{}.VerifyPresentation(SuitePlain, c.PresentedJWP, unhex(t, c.IssuerPK))
	if err != nil {
		t.Fatalf("VerifyPresentation: %v", err)
	}
	if got.Vct != c.Vct {
		t.Fatalf("vct = %q, want %q", got.Vct, c.Vct)
	}
	want := []DisclosedClaim{
		{Pointer: "/address/country", Value: json.RawMessage(`"SE"`)},
		{Pointer: "/given_name", Value: json.RawMessage(`"Alice"`)},
	}
	if len(got.Disclosed) != len(want) {
		t.Fatalf("disclosed %d claims, want %d: %+v", len(got.Disclosed), len(want), got.Disclosed)
	}
	for i, w := range want {
		if got.Disclosed[i].Pointer != w.Pointer || string(got.Disclosed[i].Value) != string(w.Value) {
			t.Fatalf("claim %d = %s %s, want %s %s", i,
				got.Disclosed[i].Pointer, got.Disclosed[i].Value, w.Pointer, w.Value)
		}
	}
	// Nothing else may leak: the credential has eight claims and two were
	// asked for.
	for _, d := range got.Disclosed {
		if d.Pointer == "/family_name" || d.Pointer == "/device_pin_hash" {
			t.Fatalf("withheld claim %s was disclosed", d.Pointer)
		}
	}
}

func TestVerifyPresentationRejectsBadInput(t *testing.T) {
	c := loadJWP(t, "plain")
	pk := unhex(t, c.IssuerPK)

	t.Run("a swapped payload", func(t *testing.T) {
		parts := strings.Split(c.PresentedJWP, ".")
		payloads := strings.Split(parts[2], "~")
		for i, p := range payloads {
			if p != "" {
				payloads[i] = base64.RawURLEncoding.EncodeToString([]byte(`"Mallory"`))
				break
			}
		}
		parts[2] = strings.Join(payloads, "~")
		if _, err := (Native{}).VerifyPresentation(SuitePlain, strings.Join(parts, "."), pk); err == nil {
			t.Fatal("verifier accepted a swapped payload")
		}
	})

	t.Run("a different issuer key", func(t *testing.T) {
		other := append([]byte(nil), pk...)
		other[0] ^= 0x01
		if _, err := (Native{}).VerifyPresentation(SuitePlain, c.PresentedJWP, other); err == nil {
			t.Fatal("verifier accepted a presentation under a different key")
		}
	})

	t.Run("the wrong suite", func(t *testing.T) {
		if _, err := (Native{}).VerifyPresentation(SuiteSchnorr, c.PresentedJWP, pk); err == nil {
			t.Fatal("verifier accepted a presentation under the wrong suite")
		}
	})

	t.Run("an issued credential rather than a presentation", func(t *testing.T) {
		if _, err := (Native{}).VerifyPresentation(SuitePlain, c.IssuedJWP, pk); err == nil {
			t.Fatal("verifier accepted an issued JWP as a presentation")
		}
	})

	t.Run("not a JWP at all", func(t *testing.T) {
		for _, bad := range []string{"", "....", "not.a.jwp", "\xff\xfe"} {
			if _, err := (Native{}).VerifyPresentation(SuitePlain, bad, pk); err == nil {
				t.Fatalf("verifier accepted %q", bad)
			}
		}
	})
}
